<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ZoomAutoAdmit.UIAutomation</RootNamespace>
    <AssemblyName>ZoomAutoAdmit.UIAutomation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FlaUI.Core" Version="4.0.0" />
    <PackageReference Include="FlaUI.UIA3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZoomAutoAdmit.Core\ZoomAutoAdmit.Core.csproj" />
  </ItemGroup>

</Project>
