<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZoomAutoAdmit.Inspector</RootNamespace>
    <AssemblyName>ZoomAutoAdmit.Inspector</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZoomAutoAdmit.Core\ZoomAutoAdmit.Core.csproj" />
    <ProjectReference Include="..\ZoomAutoAdmit.UIAutomation\ZoomAutoAdmit.UIAutomation.csproj" />
    <ProjectReference Include="..\ZoomAutoAdmit.WebAutomation\ZoomAutoAdmit.WebAutomation.csproj" />
  </ItemGroup>

</Project>
